// Generated from the recovered TikTok Web IM registry.
// Build-specific data: do not edit by hand.

export type TikTokApiEntry = {
  cmd: number;
  symbol: string;
  route: string | null;
  classification: string | null;
  requestBodyField: string | null;
  requestBodyNumber: number | null;
  requestType: string | null;
  responseBodyField: string | null;
  responseBodyNumber: number | null;
  responseType: string | null;
};

export const TIKTOK_IM_API = [
  {
    "cmd": 0,
    "symbol": "IMCMD_NOT_USED",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 100,
    "symbol": "SEND_MESSAGE",
    "route": "v1/message/send",
    "classification": "http",
    "requestBodyField": "send_message_body",
    "requestBodyNumber": 100,
    "requestType": "SendMessageRequestBody",
    "responseBodyField": "send_message_body",
    "responseBodyNumber": 100,
    "responseType": "SendMessageResponseBody"
  },
  {
    "cmd": 200,
    "symbol": "GET_MESSAGES_BY_USER",
    "route": "v1/message/get_by_user",
    "classification": "http",
    "requestBodyField": "messages_per_user_body",
    "requestBodyNumber": 200,
    "requestType": "MessagesPerUserRequestBody",
    "responseBodyField": "messages_per_user_body",
    "responseBodyNumber": 200,
    "responseType": "MessagesPerUserResponseBody"
  },
  {
    "cmd": 201,
    "symbol": "GET_MESSAGES_BY_USER_INIT",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "messages_per_user_init_body",
    "requestBodyNumber": 201,
    "requestType": "MessagesPerUserInitRequestBody",
    "responseBodyField": "messages_per_user_init_body",
    "responseBodyNumber": 201,
    "responseType": "MessagesPerUserInitResponseBody"
  },
  {
    "cmd": 202,
    "symbol": "REPORT_GET_MESSAGES_CURSOR",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 203,
    "symbol": "GET_MESSAGES_BY_USER_INIT_V2",
    "route": "v2/message/get_by_user_init",
    "classification": "http",
    "requestBodyField": "messages_per_user_init_v2_body",
    "requestBodyNumber": 203,
    "requestType": "MessagesPerUserInitV2RequestBody",
    "responseBodyField": "messages_per_user_init_v2_body",
    "responseBodyNumber": 203,
    "responseType": "MessagesPerUserInitV2ResponseBody"
  },
  {
    "cmd": 204,
    "symbol": "GET_MESSAGES_BY_USER_COMBO",
    "route": "v1/message/get_by_user_combo",
    "classification": "http",
    "requestBodyField": "messages_per_user_combo_body",
    "requestBodyNumber": 204,
    "requestType": "MessagesPerUserComboRequestBody",
    "responseBodyField": "messages_per_user_combo_body",
    "responseBodyNumber": 204,
    "responseType": "MessagesPerUserComboResponseBody"
  },
  {
    "cmd": 206,
    "symbol": "GET_MESSAGES_BY_CONVERSATION_SEARCH",
    "route": "v1/message/v1/message/get_by_conversation_search",
    "classification": "http",
    "requestBodyField": "messages_per_conversation_search_body",
    "requestBodyNumber": 206,
    "requestType": "MessagesPerConversationSearchRequestBody",
    "responseBodyField": "messages_per_conversation_search_body",
    "responseBodyNumber": 206,
    "responseType": "MessagesPerConversationSearchResponseBody"
  },
  {
    "cmd": 210,
    "symbol": "CHECK_MESSAGES_BY_USER",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "check_messages_per_user_body",
    "requestBodyNumber": 210,
    "requestType": "CheckMessagePerUserRequestBody",
    "responseBodyField": "check_messages_per_user_body",
    "responseBodyNumber": 210,
    "responseType": "CheckMessagesPerUserResponseBody"
  },
  {
    "cmd": 211,
    "symbol": "GET_MESSAGE_INFO_BY_SERVER_ID",
    "route": "v1/message/get_by_id",
    "classification": "http",
    "requestBodyField": "get_message_by_id_body",
    "requestBodyNumber": 211,
    "requestType": "GetMessageByIdRequestBody",
    "responseBodyField": "get_message_by_id_body",
    "responseBodyNumber": 211,
    "responseType": "GetMessageByIdResponseBody"
  },
  {
    "cmd": 300,
    "symbol": "GET_CONVERSATION_LIST",
    "route": "v1/conversation/get_list",
    "classification": "http",
    "requestBodyField": "conversations_list_body",
    "requestBodyNumber": 300,
    "requestType": "ConversationsListRequestBody",
    "responseBodyField": "conversations_list_body",
    "responseBodyNumber": 300,
    "responseType": "ConversationsListResponseBody"
  },
  {
    "cmd": 301,
    "symbol": "GET_MESSAGES_BY_CONVERSATION",
    "route": "v1/message/get_by_conversation",
    "classification": "http",
    "requestBodyField": "messages_in_conversation_body",
    "requestBodyNumber": 301,
    "requestType": "MessagesInConversationRequestBody",
    "responseBodyField": "messages_in_conversation_body",
    "responseBodyNumber": 301,
    "responseType": "MessagesInConversationResponseBody"
  },
  {
    "cmd": 302,
    "symbol": "GET_MESSAGES_CHECKINFO_IN_CONVERSATION",
    "route": "v1/message/get_checkinfo",
    "classification": "http",
    "requestBodyField": "get_messages_checkinfo_in_conversation_body",
    "requestBodyNumber": 302,
    "requestType": "GetMessagesCheckInfoInConversationRequestBody",
    "responseBodyField": "get_messages_checkinfo_in_conversation_body",
    "responseBodyNumber": 302,
    "responseType": "GetMessagesCheckInfoInConversationResponseBody"
  },
  {
    "cmd": 303,
    "symbol": "GET_MESSAGES_CHECK_INFO_V2",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_messages_check_info_v2_body",
    "requestBodyNumber": 303,
    "requestType": "GetMessagesCheckInfoV2RequestBody",
    "responseBodyField": "get_message_check_info_v2_body",
    "responseBodyNumber": 303,
    "responseType": "GetMessagesCheckInfoV2ResponseBody"
  },
  {
    "cmd": 304,
    "symbol": "GET_MESSAGES_BY_CONVERSATION_WITH_RANGE",
    "route": "v1/message/get_by_conversation_with_range",
    "classification": "http",
    "requestBodyField": "messages_in_conversation_with_range",
    "requestBodyNumber": 304,
    "requestType": "MessagesInConversationWithRangeRequestBody",
    "responseBodyField": "messages_in_conversation_with_range",
    "responseBodyNumber": 304,
    "responseType": "MessagesInConversationWithRangeResponseBody"
  },
  {
    "cmd": 400,
    "symbol": "SEND_ONLINE",
    "route": "v1/account/online",
    "classification": "http",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 401,
    "symbol": "SEND_OFFLINE",
    "route": "v1/account/offline",
    "classification": "http",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 402,
    "symbol": "SEND_CLIENT_FOREGROUND",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 403,
    "symbol": "SEND_CLIENT_BACKGROUND",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 410,
    "symbol": "SEND_USER_ACTION",
    "route": "v1/client/user_action",
    "classification": "http",
    "requestBodyField": "send_user_action_body",
    "requestBodyNumber": 410,
    "requestType": "SendUserActionRequestBody",
    "responseBodyField": "send_user_action_body",
    "responseBodyNumber": 410,
    "responseType": "SendUserActionResponseBody"
  },
  {
    "cmd": 411,
    "symbol": "SEND_INPUT_STATUS",
    "route": "v1/client/input_status",
    "classification": "http",
    "requestBodyField": "send_input_status_body",
    "requestBodyNumber": 411,
    "requestType": "SendInputStatusRequestBody",
    "responseBodyField": "send_input_status_body",
    "responseBodyNumber": 411,
    "responseType": "SendInputStatusResponseBody"
  },
  {
    "cmd": 500,
    "symbol": "NEW_MSG_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "has_new_message_notify",
    "responseBodyNumber": 500,
    "responseType": "NewMessageNotify"
  },
  {
    "cmd": 501,
    "symbol": "MARK_READ_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "mark_conversation_read_notify",
    "responseBodyNumber": 501,
    "responseType": "MarkConversationReadNotify"
  },
  {
    "cmd": 502,
    "symbol": "CONVERSATION_INFO_UPDATED_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "conversation_info_updated_notify",
    "responseBodyNumber": 502,
    "responseType": "ConversationInfoUpdatedNotify"
  },
  {
    "cmd": 504,
    "symbol": "NEW_DIRECT_PUSH_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "has_new_direct_push_notify",
    "responseBodyNumber": 504,
    "responseType": "NewDirectPushNotify"
  },
  {
    "cmd": 505,
    "symbol": "NEW_BROADCAST_MSG_NOTIFY",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 506,
    "symbol": "NEW_BROADCAST_CMD_MSG_NOTIFY",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 507,
    "symbol": "NEW_PREVIEW_MSG_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "new_friend_message_notify",
    "responseBodyNumber": 507,
    "responseType": "NewFriendMessageNotify"
  },
  {
    "cmd": 508,
    "symbol": "NEW_FRIEND_MSG_NOTIFY",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 510,
    "symbol": "NEW_INPUT_STATUS_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "input_status_notify",
    "responseBodyNumber": 510,
    "responseType": "InputStatusNotify"
  },
  {
    "cmd": 511,
    "symbol": "BIZ_DIRECT_PUSH_NOTIFY",
    "route": null,
    "classification": "notify/response-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": "biz_has_new_direct_push_notify",
    "responseBodyNumber": 511,
    "responseType": "BizNewDirectPushNotify"
  },
  {
    "cmd": 600,
    "symbol": "GET_CONVERSATION_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_info_body",
    "requestBodyNumber": 600,
    "requestType": "GetConversationInfoRequestBody",
    "responseBodyField": "get_conversation_info_body",
    "responseBodyNumber": 600,
    "responseType": "GetConversationInfoResponseBody"
  },
  {
    "cmd": 601,
    "symbol": "SET_CONVERSATION_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "set_conversation_info_body",
    "requestBodyNumber": 601,
    "requestType": "SetConversationInfoRequestBody",
    "responseBodyField": "set_conversation_info_body",
    "responseBodyNumber": 601,
    "responseType": "SetConversationInfoResponseBody"
  },
  {
    "cmd": 602,
    "symbol": "CREATE_CONVERSATION",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "create_conversation_body",
    "requestBodyNumber": 602,
    "requestType": "CreateConversationRequestBody",
    "responseBodyField": "create_conversation_body",
    "responseBodyNumber": 602,
    "responseType": "CreateConversationResponseBody"
  },
  {
    "cmd": 603,
    "symbol": "MARK_CONVERSATION_DELETE",
    "route": "v1/conversation/delete",
    "classification": "http",
    "requestBodyField": "delete_conversation_body",
    "requestBodyNumber": 603,
    "requestType": "DeleteConversationRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 604,
    "symbol": "MARK_CONVERSATION_READ",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "mark_conversation_read_body",
    "requestBodyNumber": 604,
    "requestType": "MarkConversationReadRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 605,
    "symbol": "CONVERSATION_PARTICIPANTS_LIST",
    "route": "v1/conversation/participants_list",
    "classification": "http",
    "requestBodyField": "conversation_participants_body",
    "requestBodyNumber": 605,
    "requestType": "ConversationParticipantsListRequestBody",
    "responseBodyField": "conversation_participants_body",
    "responseBodyNumber": 605,
    "responseType": "ConversationParticipantsListResponseBody"
  },
  {
    "cmd": 607,
    "symbol": "GET_CONVERSATION_INFO_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_info_list_body",
    "requestBodyNumber": 607,
    "requestType": "GetConversationInfoListRequestBody",
    "responseBodyField": "get_conversations_info_list_body",
    "responseBodyNumber": 607,
    "responseType": "GetConversationInfoListResponseBody"
  },
  {
    "cmd": 608,
    "symbol": "GET_CONVERSATION_INFO_V2",
    "route": "v2/conversation/get_info",
    "classification": "http",
    "requestBodyField": "get_conversation_info_v2_body",
    "requestBodyNumber": 608,
    "requestType": "GetConversationInfoV2RequestBody",
    "responseBodyField": "get_conversation_info_v2_body",
    "responseBodyNumber": 608,
    "responseType": "GetConversationInfoV2ResponseBody"
  },
  {
    "cmd": 609,
    "symbol": "CREATE_CONVERSATION_V2",
    "route": "v2/conversation/create",
    "classification": "http",
    "requestBodyField": "create_conversation_v2_body",
    "requestBodyNumber": 609,
    "requestType": "CreateConversationV2RequestBody",
    "responseBodyField": "create_conversation_v2_body",
    "responseBodyNumber": 609,
    "responseType": "CreateConversationV2ResponseBody"
  },
  {
    "cmd": 610,
    "symbol": "GET_CONVERSATION_INFO_LIST_V2",
    "route": "v2/conversation/get_info_list",
    "classification": "http",
    "requestBodyField": "get_conversation_info_list_v2_body",
    "requestBodyNumber": 610,
    "requestType": "GetConversationInfoListV2RequestBody",
    "responseBodyField": "get_conversation_info_list_v2_body",
    "responseBodyNumber": 610,
    "responseType": "GetConversationInfoListV2ResponseBody"
  },
  {
    "cmd": 611,
    "symbol": "GET_CONVERSATION_INFO_LIST_BY_FAVORITE_V2",
    "route": "v2/conversation/get_by_favorite",
    "classification": "http",
    "requestBodyField": "get_conversation_info_list_by_favorite_v2_body",
    "requestBodyNumber": 611,
    "requestType": "ConversationsPerUserByFavoriteV2RequestBody",
    "responseBodyField": "get_conversation_info_list_by_favorite_v2_body",
    "responseBodyNumber": 611,
    "responseType": "GetConversationInfoListByFavoriteV2ResponseBody"
  },
  {
    "cmd": 612,
    "symbol": "GET_CONVERSATION_INFO_LIST_BY_TOP_V2",
    "route": "v2/conversation/get_by_top",
    "classification": "http",
    "requestBodyField": "get_conversation_info_list_by_top_v2_body",
    "requestBodyNumber": 612,
    "requestType": "ConversationsPerUserByTopV2RequestBody",
    "responseBodyField": "get_conversation_info_list_by_top_v2_body",
    "responseBodyNumber": 612,
    "responseType": "GetConversationInfoListByTopV2ResponseBody"
  },
  {
    "cmd": 613,
    "symbol": "BATCH_MARK_CONVERSATION_READ",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "batch_mark_read_body",
    "requestBodyNumber": 613,
    "requestType": "BatchMarkConversationReadRequestBody",
    "responseBodyField": "batch_mark_read_body",
    "responseBodyNumber": 613,
    "responseType": "BatchMarkConversationReadResponseBody"
  },
  {
    "cmd": 614,
    "symbol": "DISSOLVE_CONVERSATION",
    "route": "v1/conversation/dissolve",
    "classification": "http",
    "requestBodyField": "dissolve_conversation_body",
    "requestBodyNumber": 614,
    "requestType": "DissolveConversationRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 615,
    "symbol": "GET_CONVERSATIONS_CHECKINFO",
    "route": "v1/conversation/get_checkinfo",
    "classification": "http",
    "requestBodyField": "get_conversations_checkinfo_body",
    "requestBodyNumber": 615,
    "requestType": "GetConversationsCheckInfoRequestBody",
    "responseBodyField": "get_conversations_checkinfo_body",
    "responseBodyNumber": 615,
    "responseType": "GetConversationsCheckInfoResponseBody"
  },
  {
    "cmd": 616,
    "symbol": "GET_CONVERSATIONS_CHECK_INFO_V2",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_check_info_v2_body",
    "requestBodyNumber": 616,
    "requestType": "GetConversationsCheckInfoV2RequestBody",
    "responseBodyField": "get_conversations_check_info_v2_body",
    "responseBodyNumber": 616,
    "responseType": "GetConversationsCheckInfoV2ResponseBody"
  },
  {
    "cmd": 617,
    "symbol": "BATCH_DELETE_CONVERSATIONS",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 650,
    "symbol": "ADD_CONVERSATION_PARTICIPANTS",
    "route": "v1/conversation/add_participants",
    "classification": "http",
    "requestBodyField": "conversation_add_participants_body",
    "requestBodyNumber": 650,
    "requestType": "ConversationAddParticipantsRequestBody",
    "responseBodyField": "conversation_add_participants_body",
    "responseBodyNumber": 650,
    "responseType": "ConversationAddParticipantsResponseBody"
  },
  {
    "cmd": 651,
    "symbol": "REMOVE_CONVERSATION_PARTICIPANTS",
    "route": "v1/conversation/remove_participants",
    "classification": "http",
    "requestBodyField": "conversation_remove_participants_body",
    "requestBodyNumber": 651,
    "requestType": "ConversationRemoveParticipantsRequestBody",
    "responseBodyField": "conversation_remove_participants_body",
    "responseBodyNumber": 651,
    "responseType": "ConversationRemoveParticipantsResponseBody"
  },
  {
    "cmd": 652,
    "symbol": "LEAVE_CONVERSATION",
    "route": "v1/conversation/leave",
    "classification": "http",
    "requestBodyField": "leave_conversation_body",
    "requestBodyNumber": 652,
    "requestType": "ConversationLeaveRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 653,
    "symbol": "CONVERSATION_SET_ROLE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "conversation_set_role_body",
    "requestBodyNumber": 653,
    "requestType": "ConversationSetRoleRequestBody",
    "responseBodyField": "conversation_set_role_body",
    "responseBodyNumber": 653,
    "responseType": "ConversationSetRoleResponseBody"
  },
  {
    "cmd": 654,
    "symbol": "MGET_CONVERSATION_PARTICIPANTS",
    "route": "v1/conversation/mget_participants",
    "classification": "http",
    "requestBodyField": "mget_conversation_participants_body",
    "requestBodyNumber": 654,
    "requestType": "MgetConversationParticipantsRequestBody",
    "responseBodyField": "mget_conversation_participants_body",
    "responseBodyNumber": 654,
    "responseType": "MgetConversationParticipantsResponseBody"
  },
  {
    "cmd": 655,
    "symbol": "UPDATE_CONVERSATION_PARTICIPANT",
    "route": "v1/conversation/update_participant",
    "classification": "http",
    "requestBodyField": "update_conversation_participant_body",
    "requestBodyNumber": 655,
    "requestType": "UpdateConversationParticipantRequestBody",
    "responseBodyField": "update_conversation_participant_body",
    "responseBodyNumber": 655,
    "responseType": "UpdateConversationParticipantResponseBody"
  },
  {
    "cmd": 656,
    "symbol": "BATCH_UPDATE_CONVERSATION_PARTICIPANT",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "batch_update_conversation_participant_body",
    "requestBodyNumber": 656,
    "requestType": "BatchUpdateConversationParticipantRequestBody",
    "responseBodyField": "batch_update_conversation_participant_body",
    "responseBodyNumber": 656,
    "responseType": "BatchUpdateConversationParticipantResponseBody"
  },
  {
    "cmd": 690,
    "symbol": "GET_CONVERSATION_GROUP_LIST",
    "route": "v1/conversation/get_group_list",
    "classification": "http",
    "requestBodyField": "get_conversation_group_list_body",
    "requestBodyNumber": 690,
    "requestType": "GetConversationGroupListRequestBody",
    "responseBodyField": "get_conversation_group_list_body",
    "responseBodyNumber": 690,
    "responseType": "GetConversationGroupListResponseBody"
  },
  {
    "cmd": 701,
    "symbol": "DELETE_MESSAGE",
    "route": "v1/message/delete",
    "classification": "http",
    "requestBodyField": "delete_message_body",
    "requestBodyNumber": 701,
    "requestType": "DeleteMessageRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 702,
    "symbol": "RECALL_MESSAGE",
    "route": "v1/message/recall",
    "classification": "http",
    "requestBodyField": "recall_message_body",
    "requestBodyNumber": 702,
    "requestType": "RecallMessageRequestBody",
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 703,
    "symbol": "REACTION_MESSAGE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "reaction_message_body",
    "requestBodyNumber": 703,
    "requestType": "ReactionMessageRequestBody",
    "responseBodyField": "reaction_message_body",
    "responseBodyNumber": 703,
    "responseType": "ReactionMessageResponseBody"
  },
  {
    "cmd": 704,
    "symbol": "SYNC_MESSAGE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "sync_message_body",
    "requestBodyNumber": 704,
    "requestType": "SyncMessageRequestBody",
    "responseBodyField": "sync_message_body",
    "responseBodyNumber": 704,
    "responseType": "SyncMessageResponseBody"
  },
  {
    "cmd": 705,
    "symbol": "SET_MESSAGE_PROPERTY",
    "route": "v1/message/set_property",
    "classification": "http",
    "requestBodyField": "modify_message_property_body",
    "requestBodyNumber": 705,
    "requestType": "ModifyMessagePropertyRequestBody",
    "responseBodyField": "modify_message_property_body",
    "responseBodyNumber": 705,
    "responseType": "ModifyMessagePropertyResponseBody"
  },
  {
    "cmd": 706,
    "symbol": "ACK_MESSAGE",
    "route": "v1/message/ack",
    "classification": "http",
    "requestBodyField": "ack_message_body",
    "requestBodyNumber": 706,
    "requestType": "AckMessageRequestBody",
    "responseBodyField": "ack_message_body",
    "responseBodyNumber": 706,
    "responseType": "AckMessageResponseBody"
  },
  {
    "cmd": 801,
    "symbol": "GET_GROUP_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_group_info_body",
    "requestBodyNumber": 801,
    "requestType": "GetGroupInfoRequestBody",
    "responseBodyField": "get_group_info_body",
    "responseBodyNumber": 801,
    "responseType": "GetGroupInfoResponseBody"
  },
  {
    "cmd": 802,
    "symbol": "SET_GROUP_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "set_group_info_body",
    "requestBodyNumber": 802,
    "requestType": "SetGroupInfoRequestBody",
    "responseBodyField": "set_group_info_body",
    "responseBodyNumber": 802,
    "responseType": "SetGroupInfoResponseBody"
  },
  {
    "cmd": 803,
    "symbol": "GET_GROUP_INFO_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_group_info_list_body",
    "requestBodyNumber": 803,
    "requestType": "GetGroupInfoListRequestBody",
    "responseBodyField": "get_groups_info_body",
    "responseBodyNumber": 803,
    "responseType": "GetGroupInfoListResponseBody"
  },
  {
    "cmd": 901,
    "symbol": "GET_CONVERSATION_CORE_INFO",
    "route": "v1/conversation/get_core_info",
    "classification": "http",
    "requestBodyField": "get_conversation_core_info_body",
    "requestBodyNumber": 901,
    "requestType": "GetConversationCoreInfoRequestBody",
    "responseBodyField": "get_conversation_core_info_body",
    "responseBodyNumber": 901,
    "responseType": "GetConversationCoreInfoResponseBody"
  },
  {
    "cmd": 902,
    "symbol": "SET_CONVERSATION_CORE_INFO",
    "route": "v1/conversation/set_core_info",
    "classification": "http",
    "requestBodyField": "set_conversation_core_info_body",
    "requestBodyNumber": 902,
    "requestType": "SetConversationCoreInfoRequestBody",
    "responseBodyField": "set_conversation_core_info_body",
    "responseBodyNumber": 902,
    "responseType": "SetConversationCoreInfoResponseBody"
  },
  {
    "cmd": 903,
    "symbol": "GET_CONVERSATION_CORE_INFO_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_core_info_list_body",
    "requestBodyNumber": 903,
    "requestType": "GetConversationCoreInfoListRequestBody",
    "responseBodyField": "get_conversation_core_info_list_body",
    "responseBodyNumber": 903,
    "responseType": "GetConversationCoreInfoListResponseBody"
  },
  {
    "cmd": 904,
    "symbol": "UPSERT_CONVERSATION_CORE_EXT_INFO",
    "route": "v1/conversation/upsert_core_ext_info",
    "classification": "http",
    "requestBodyField": "upsert_conversation_core_ext_info_body",
    "requestBodyNumber": 904,
    "requestType": "UpsertConversationCoreExtInfoRequestBody",
    "responseBodyField": "upsert_conversation_core_ext_info_body",
    "responseBodyNumber": 904,
    "responseType": "UpsertConversationCoreExtInfoResponseBody"
  },
  {
    "cmd": 920,
    "symbol": "GET_CONVERSATION_SETTING_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_setting_info_body",
    "requestBodyNumber": 920,
    "requestType": "GetConversationSettingInfoRequestBody",
    "responseBodyField": "get_conversation_setting_info_body",
    "responseBodyNumber": 920,
    "responseType": "GetConversationSettingInfoResponseBody"
  },
  {
    "cmd": 921,
    "symbol": "SET_CONVERSATION_SETTING_INFO",
    "route": "v1/conversation/set_setting_info",
    "classification": "http",
    "requestBodyField": "set_conversation_setting_info_body",
    "requestBodyNumber": 921,
    "requestType": "SetConversationSettingInfoRequestBody",
    "responseBodyField": "set_conversation_setting_info_body",
    "responseBodyNumber": 921,
    "responseType": "SetConversationSettingInfoResponseBody"
  },
  {
    "cmd": 922,
    "symbol": "UPSERT_CONVERSATION_SETTING_EXT_INFO",
    "route": "v1/conversation/upsert_settings_ext",
    "classification": "http",
    "requestBodyField": "upsert_conversation_setting_ext_info_body",
    "requestBodyNumber": 922,
    "requestType": "UpsertConversationSettingExtInfoRequestBody",
    "responseBodyField": "upsert_conversation_setting_ext_info_body",
    "responseBodyNumber": 922,
    "responseType": "UpsertConversationSettingExtInfoResponseBody"
  },
  {
    "cmd": 1001,
    "symbol": "GET_STRANGER_CONVERSATION_LIST",
    "route": "v1/stranger/get_conversation_list",
    "classification": "http",
    "requestBodyField": "get_stranger_messages_body",
    "requestBodyNumber": 1001,
    "requestType": "GetStrangerMessagesRequestBody",
    "responseBodyField": "get_stranger_messages_body",
    "responseBodyNumber": 1001,
    "responseType": "GetStrangerMessagesResponseBody"
  },
  {
    "cmd": 1002,
    "symbol": "GET_STRANGER_MESSAGES_IN_CONVERSATION",
    "route": "v1/stranger/get_messages",
    "classification": "http",
    "requestBodyField": "delete_stranger_message_body",
    "requestBodyNumber": 1002,
    "requestType": "DeleteStrangerMessageRequestBody",
    "responseBodyField": "delete_stranger_message_body",
    "responseBodyNumber": 1002,
    "responseType": "DeleteStrangerMessageResponseBody"
  },
  {
    "cmd": 1003,
    "symbol": "DELETE_STRANGER_MESSAGE",
    "route": "v1/stranger/delete_message",
    "classification": "http",
    "requestBodyField": "delete_stranger_conversation_body",
    "requestBodyNumber": 1003,
    "requestType": "DeleteStrangerConversationRequestBody",
    "responseBodyField": "delete_stranger_conversation_body",
    "responseBodyNumber": 1003,
    "responseType": "DeleteStrangerConversationResponseBody"
  },
  {
    "cmd": 1004,
    "symbol": "DELETE_STRANGER_CONVERSATION",
    "route": "v1/stranger/delete_conversation",
    "classification": "http",
    "requestBodyField": "delete_stranger_all_conversation_body",
    "requestBodyNumber": 1004,
    "requestType": "DeleteStrangerAllConversationRequestBody",
    "responseBodyField": "delete_stranger_all_conversation_body",
    "responseBodyNumber": 1004,
    "responseType": "DeleteStrangerAllConversationResponseBody"
  },
  {
    "cmd": 1005,
    "symbol": "DELETE_ALL_STRANGER_CONVERSATIONS",
    "route": "v1/stranger/delete_all_conversations",
    "classification": "http",
    "requestBodyField": "mark_stranger_conversation_read_body",
    "requestBodyNumber": 1005,
    "requestType": "MarkStrangerConversationReadRequestBody",
    "responseBodyField": "mark_stranger_conversation_read_body",
    "responseBodyNumber": 1005,
    "responseType": "MarkStrangerConversationReadResponseBody"
  },
  {
    "cmd": 1006,
    "symbol": "MARK_STRANGER_CONVERSATION_READ",
    "route": "v1/stranger/mark_read_conversation",
    "classification": "http",
    "requestBodyField": "mark_stranger_all_conversation_read_body",
    "requestBodyNumber": 1006,
    "requestType": "MarkStrangerAllConversationReadRequestBody",
    "responseBodyField": "mark_stranger_all_conversation_read_body",
    "responseBodyNumber": 1006,
    "responseType": "MarkStrangerAllConversationReadResponseBody"
  },
  {
    "cmd": 1007,
    "symbol": "MARK_ALL_STRANGER_CONVERSATIONS_READ",
    "route": "v1/stranger/mark_read_all_conversations",
    "classification": "http",
    "requestBodyField": "get_stranger_unread_count_body",
    "requestBodyNumber": 1007,
    "requestType": "GetStrangerUnreadCountRequestBody",
    "responseBodyField": "get_stranger_unread_count_body",
    "responseBodyNumber": 1007,
    "responseType": "GetStrangerUnreadCountResponseBody"
  },
  {
    "cmd": 1008,
    "symbol": "GET_STRANGER_UNREAD_COUNT",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 1099,
    "symbol": "STRANGER_NEW_MSG_NOTIFY",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 2000,
    "symbol": "GET_CONVERSATION_PARTICIPANTS_READ_INDEX_V3",
    "route": "v3/conversation/get_read_index",
    "classification": "http",
    "requestBodyField": "participants_read_index_body",
    "requestBodyNumber": 2000,
    "requestType": "GetConversationParticipantsReadIndexV3RequestBody",
    "responseBodyField": "participants_read_index_body",
    "responseBodyNumber": 2000,
    "responseType": "GetConversationParticipantsReadIndexV3ResponseBody"
  },
  {
    "cmd": 2001,
    "symbol": "GET_CONVERSATION_PARTICIPANTS_MIN_INDEX_V3",
    "route": "v3/conversation/get_min_index",
    "classification": "http",
    "requestBodyField": "participants_min_index_body",
    "requestBodyNumber": 2001,
    "requestType": "GetConversationParticipantsMinIndexV3RequestBody",
    "responseBodyField": "participants_min_index_body",
    "responseBodyNumber": 2001,
    "responseType": "GetConversationParticipantsMinIndexV3ResponseBody"
  },
  {
    "cmd": 2002,
    "symbol": "MARK_CONVERSATION_READ_V3",
    "route": "v3/conversation/mark_read",
    "classification": "http",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 2003,
    "symbol": "GET_MEDIA_UPLOAD_TOKEN",
    "route": "tiktok/v1/im/upload_config",
    "classification": "http",
    "requestBodyField": "get_upload_token_body",
    "requestBodyNumber": 2003,
    "requestType": "GetUploadTokenRequestBody",
    "responseBodyField": "get_upload_token_body",
    "responseBodyNumber": 2003,
    "responseType": "GetUploadTokenResponseBody"
  },
  {
    "cmd": 2004,
    "symbol": "GET_MEDIA_URLS",
    "route": "v1/media/get_urls",
    "classification": "http",
    "requestBodyField": "get_media_urls_body",
    "requestBodyNumber": 2004,
    "requestType": "GetMediaUrlsRequestBody",
    "responseBodyField": "get_media_urls_body",
    "responseBodyNumber": 2004,
    "responseType": "GetMediaUrlsResponseBody"
  },
  {
    "cmd": 2005,
    "symbol": "GET_TICKET",
    "route": "v1/conversation/get_ticket",
    "classification": "http",
    "requestBodyField": "get_ticket_body",
    "requestBodyNumber": 2005,
    "requestType": "GetTicketRequestBody",
    "responseBodyField": "get_ticket_body",
    "responseBodyNumber": 2005,
    "responseType": "GetTicketResponseBody"
  },
  {
    "cmd": 2006,
    "symbol": "GET_USER_CONVERSATION_LIST",
    "route": "v1/conversation/list",
    "classification": "http",
    "requestBodyField": "get_conversation_list_body",
    "requestBodyNumber": 2006,
    "requestType": "GetUserConversationListRequestBody",
    "responseBodyField": "get_conversation_list_body",
    "responseBodyNumber": 2006,
    "responseType": "GetUserConversationListResponseBody"
  },
  {
    "cmd": 2007,
    "symbol": "BROADCAST_SEND_MESSAGE",
    "route": "v1/broadcast/send_message",
    "classification": "http",
    "requestBodyField": "broadcast_send_message_body",
    "requestBodyNumber": 2007,
    "requestType": "BroadcastSendMessageRequestBody",
    "responseBodyField": "broadcast_send_message_body",
    "responseBodyNumber": 2007,
    "responseType": "BroadcastSendMessageResponseBody"
  },
  {
    "cmd": 2008,
    "symbol": "BROADCAST_RECV_MESSAGE",
    "route": "v1/broadcast/recv_message",
    "classification": "http",
    "requestBodyField": "broadcast_recv_message_body",
    "requestBodyNumber": 2008,
    "requestType": "BroadcastRecvMessageRequestBody",
    "responseBodyField": "broadcast_recv_message_body",
    "responseBodyNumber": 2008,
    "responseType": "BroadcastRecvMessageResponseBody"
  },
  {
    "cmd": 2009,
    "symbol": "BROADCAST_USER_COUNTER",
    "route": "v1/broadcast/user_counter",
    "classification": "http",
    "requestBodyField": "broadcast_user_counter_body",
    "requestBodyNumber": 2009,
    "requestType": "BroadcastUserCounterRequestBody",
    "responseBodyField": "broadcast_user_counter_body",
    "responseBodyNumber": 2009,
    "responseType": "BroadcastUserCounterResponseBody"
  },
  {
    "cmd": 2010,
    "symbol": "CLIENT_ACK",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "client_ack_body",
    "requestBodyNumber": 2010,
    "requestType": "ClientACKRequestBody",
    "responseBodyField": "client_ack_body",
    "responseBodyNumber": 2010,
    "responseType": "ClientACKResponseBody"
  },
  {
    "cmd": 2011,
    "symbol": "CREATE_VOIP",
    "route": "v1/voip/create",
    "classification": "http",
    "requestBodyField": "create_voip_body",
    "requestBodyNumber": 2011,
    "requestType": "CreateVoipRequestBody",
    "responseBodyField": "create_voip_body",
    "responseBodyNumber": 2011,
    "responseType": "CreateVoipResponseBody"
  },
  {
    "cmd": 2012,
    "symbol": "CALL_VOIP",
    "route": "v1/voip/call",
    "classification": "http",
    "requestBodyField": "call_voip_body",
    "requestBodyNumber": 2012,
    "requestType": "CallVoipRequestBody",
    "responseBodyField": "call_voip_body",
    "responseBodyNumber": 2012,
    "responseType": "CallVoipResponseBody"
  },
  {
    "cmd": 2013,
    "symbol": "UPDATE_VOIP",
    "route": "v1/voip/update",
    "classification": "http",
    "requestBodyField": "update_voip_body",
    "requestBodyNumber": 2013,
    "requestType": "UpdateVoipRequestBody",
    "responseBodyField": "update_voip_body",
    "responseBodyNumber": 2013,
    "responseType": "UpdateVoipResponseBody"
  },
  {
    "cmd": 2014,
    "symbol": "HEARTBEAT_CHANNEL",
    "route": "v1/channel/heartbeat",
    "classification": "http",
    "requestBodyField": "channel_heartbeat_body",
    "requestBodyNumber": 2014,
    "requestType": "ChannelHeartBeatRequestBody",
    "responseBodyField": "channel_heartbeat_body",
    "responseBodyNumber": 2014,
    "responseType": "ChannelHeartBeatResponseBody"
  },
  {
    "cmd": 2015,
    "symbol": "PROFILE_GET_INFO",
    "route": "v1/profile/get_info",
    "classification": "http",
    "requestBodyField": "profile_get_info",
    "requestBodyNumber": 2015,
    "requestType": "ProfileGetInfoRequestBody",
    "responseBodyField": "profile_get_info",
    "responseBodyNumber": 2015,
    "responseType": "ProfileGetInfoResponseBody"
  },
  {
    "cmd": 2016,
    "symbol": "REPORT_CLIENT_METRICS",
    "route": "v1/client/report_metrics",
    "classification": "http",
    "requestBodyField": "report_client_metrics_body",
    "requestBodyNumber": 2016,
    "requestType": "ReportClientMetricsRequestBody",
    "responseBodyField": "report_client_metrics_body",
    "responseBodyNumber": 2016,
    "responseType": "ReportClientMetricsResponseBody"
  },
  {
    "cmd": 2017,
    "symbol": "GET_CONFIGS",
    "route": "v1/config/get",
    "classification": "http",
    "requestBodyField": "get_configs_body",
    "requestBodyNumber": 2017,
    "requestType": "GetConfigsRequestBody",
    "responseBodyField": "get_configs_body",
    "responseBodyNumber": 2017,
    "responseType": "GetConfigsResponseBody"
  },
  {
    "cmd": 2018,
    "symbol": "UNREAD_COUNT_REPORT",
    "route": "v1/client/unread_count",
    "classification": "http",
    "requestBodyField": "unread_count_report_body",
    "requestBodyNumber": 2018,
    "requestType": "UnReadCountReportRequestBody",
    "responseBodyField": "unread_count_report_body",
    "responseBodyNumber": 2018,
    "responseType": "UnReadCountReportResponseBody"
  },
  {
    "cmd": 2019,
    "symbol": "BLOCK_MEMBERS",
    "route": "v1/conversation/block_member",
    "classification": "http",
    "requestBodyField": "block_members_body",
    "requestBodyNumber": 2019,
    "requestType": "BlockMembersRequestBody",
    "responseBodyField": "block_members_body",
    "responseBodyNumber": 2019,
    "responseType": "BlockMembersResponseBody"
  },
  {
    "cmd": 2020,
    "symbol": "BLOCK_CONVERSATION",
    "route": "v1/conversation/block_conversation",
    "classification": "http",
    "requestBodyField": "block_conversation_body",
    "requestBodyNumber": 2020,
    "requestType": "BlockConversationRequestBody",
    "responseBodyField": "block_conversation_body",
    "responseBodyNumber": 2020,
    "responseType": "BlockConversationResponseBody"
  },
  {
    "cmd": 2021,
    "symbol": "MODIFY_MESSAGE_EXT",
    "route": "v1/message/modify_ext",
    "classification": "http",
    "requestBodyField": "modify_message_ext_body",
    "requestBodyNumber": 2021,
    "requestType": "ModifyMessageExtRequestBody",
    "responseBodyField": "modify_message_ext_body",
    "responseBodyNumber": 2021,
    "responseType": "ModifyMessageExtResponseBody"
  },
  {
    "cmd": 2022,
    "symbol": "GET_CONVERSATION_AUDIT_SWITCH",
    "route": "v1/conversation/get_audit",
    "classification": "http",
    "requestBodyField": "get_conversation_audit_switch_body",
    "requestBodyNumber": 2022,
    "requestType": "GetConversationAuditSwitchRequestBody",
    "responseBodyField": "get_conversation_audit_switch_body",
    "responseBodyNumber": 2022,
    "responseType": "GetConversationAuditSwitchResponseBody"
  },
  {
    "cmd": 2023,
    "symbol": "UPDATE_CONVERSATION_AUDIT_SWITCH",
    "route": "v1/conversation/update_audit",
    "classification": "http",
    "requestBodyField": "update_conversation_audit_switch_body",
    "requestBodyNumber": 2023,
    "requestType": "UpdateConversationAuditSwitchRequestBody",
    "responseBodyField": "update_conversation_audit_switch_body",
    "responseBodyNumber": 2023,
    "responseType": "UpdateConversationAuditSwitchResponseBody"
  },
  {
    "cmd": 2024,
    "symbol": "SEND_CONVERSATION_APPLY",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "send_conversation_apply_body",
    "requestBodyNumber": 2024,
    "requestType": "SendConversationApplyRequestBody",
    "responseBodyField": "send_conversation_apply_body",
    "responseBodyNumber": 2024,
    "responseType": "SendConversationApplyResponseBody"
  },
  {
    "cmd": 2025,
    "symbol": "ACK_CONVERSATION_APPLY",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "ack_conversation_apply_body",
    "requestBodyNumber": 2025,
    "requestType": "AckConversationApplyRequestBody",
    "responseBodyField": "ack_conversation_apply_body",
    "responseBodyNumber": 2025,
    "responseType": "AckConversationApplyResponseBody"
  },
  {
    "cmd": 2026,
    "symbol": "GET_CONVERSATION_APPLY",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_apply_body",
    "requestBodyNumber": 2026,
    "requestType": "GetConversationApplyRequestBody",
    "responseBodyField": "get_conversation_apply_body",
    "responseBodyNumber": 2026,
    "responseType": "GetConversationApplyResponseBody"
  },
  {
    "cmd": 2027,
    "symbol": "GET_CONVERSATION_AUDIT_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_audit_list_body",
    "requestBodyNumber": 2027,
    "requestType": "GetConversationAuditListRequestBody",
    "responseBodyField": "get_conversation_audit_list_body",
    "responseBodyNumber": 2027,
    "responseType": "GetConversationAuditListResponseBody"
  },
  {
    "cmd": 2028,
    "symbol": "GET_CONVERSATION_AUDIT_UNREAD",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_conversation_audit_unread_body",
    "requestBodyNumber": 2028,
    "requestType": "GetConversationAuditUnreadRequestBody",
    "responseBodyField": "get_conversation_audit_unread_body",
    "responseBodyNumber": 2028,
    "responseType": "GetConversationAuditUnreadResponseBody"
  },
  {
    "cmd": 2029,
    "symbol": "CLEAR_CONVERSATION_AUDIT_UNREAD",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "clear_conversation_audit_unread_body",
    "requestBodyNumber": 2029,
    "requestType": "ClearConversationAuditUnreadRequestBody",
    "responseBodyField": "clear_conversation_audit_unread_body",
    "responseBodyNumber": 2029,
    "responseType": "ClearConversationAuditUnreadResponseBody"
  },
  {
    "cmd": 2030,
    "symbol": "GET_UNREAD_COUNT",
    "route": "v1/client/get_unread_count",
    "classification": "http",
    "requestBodyField": "get_unread_count_body",
    "requestBodyNumber": 2030,
    "requestType": "GetUnreadCountRequestBody",
    "responseBodyField": "get_unread_count_body",
    "responseBodyNumber": 2030,
    "responseType": "GetUnreadCountResponseBody"
  },
  {
    "cmd": 2031,
    "symbol": "SEND_MESSAGE_P2P",
    "route": "v1/send_message/p2p",
    "classification": "http",
    "requestBodyField": "send_message_p2p_body",
    "requestBodyNumber": 2031,
    "requestType": "SendMessageP2PRequestBody",
    "responseBodyField": "send_message_p2p_body",
    "responseBodyNumber": 2031,
    "responseType": "SendMessageP2PResponseBody"
  },
  {
    "cmd": 2032,
    "symbol": "GET_BLOCKLIST",
    "route": "v1/blocklist/get",
    "classification": "http",
    "requestBodyField": "get_blocklist_body",
    "requestBodyNumber": 2032,
    "requestType": "GetBlockListRequestBody",
    "responseBodyField": "get_blocklist_body",
    "responseBodyNumber": 2032,
    "responseType": "GetBlockListResponseBody"
  },
  {
    "cmd": 2033,
    "symbol": "SET_BLOCKLIST",
    "route": "v1/blocklist/set",
    "classification": "http",
    "requestBodyField": "set_blocklist_body",
    "requestBodyNumber": 2033,
    "requestType": "SetBlocklistRequestBody",
    "responseBodyField": "set_blocklist_body",
    "responseBodyNumber": 2033,
    "responseType": "SetBlocklistResponseBody"
  },
  {
    "cmd": 2034,
    "symbol": "CHECK_IN_BLOCKLIST",
    "route": "v1/blocklist/check",
    "classification": "http",
    "requestBodyField": "check_in_blocklist_body",
    "requestBodyNumber": 2034,
    "requestType": "CheckInBlockListRequestBody",
    "responseBodyField": "check_in_blocklist_body",
    "responseBodyNumber": 2034,
    "responseType": "CheckInBlockListResponseBody"
  },
  {
    "cmd": 2035,
    "symbol": "GET_MESSAGE_INFO_BY_INDEX_V2",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_message_info_by_index_v2_body",
    "requestBodyNumber": 2035,
    "requestType": "GetMessageInfoByIndexV2RequestBody",
    "responseBodyField": "get_message_info_by_index_v2_body",
    "responseBodyNumber": 2035,
    "responseType": "GetMessageInfoByIndexV2ResponseBody"
  },
  {
    "cmd": 2036,
    "symbol": "MARK_MESSAGE",
    "route": "v1/message/mark",
    "classification": "http",
    "requestBodyField": "mark_message_body",
    "requestBodyNumber": 2036,
    "requestType": "MarkMessageRequestBody",
    "responseBodyField": "mark_message_body",
    "responseBodyNumber": 2036,
    "responseType": "MarkMessageResponseBody"
  },
  {
    "cmd": 2037,
    "symbol": "PULL_MARK_MESSAGE",
    "route": "v1/message/pull_mark",
    "classification": "http",
    "requestBodyField": "pull_mark_message_body",
    "requestBodyNumber": 2037,
    "requestType": "PullMarkMessageRequestBody",
    "responseBodyField": "pull_mark_message_body",
    "responseBodyNumber": 2037,
    "responseType": "PullMarkMessageResponseBody"
  },
  {
    "cmd": 2038,
    "symbol": "BATCH_GAT_CONVERSATION_PARTICIPANTS_READINDEX",
    "route": "v1/conversation/batch_get_conversation_participants_readindex",
    "classification": "http",
    "requestBodyField": "batch_get_conversation_participants_readindex",
    "requestBodyNumber": 2038,
    "requestType": "BatchGetConversationParticipantsReadIndexRequestBody",
    "responseBodyField": "batch_get_conversation_participants_readindex",
    "responseBodyNumber": 2038,
    "responseType": "BatchGetConversationParticipantsReadIndexResponseBody"
  },
  {
    "cmd": 2039,
    "symbol": "GET_RECENT_MESSAGE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_recent_message_body",
    "requestBodyNumber": 2039,
    "requestType": "GetRecentMessageReqBody",
    "responseBodyField": "get_recent_message_body",
    "responseBodyNumber": 2039,
    "responseType": "GetRecentMessageRespBody"
  },
  {
    "cmd": 2040,
    "symbol": "GET_CMD_MESSAGE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_cmd_message_body",
    "requestBodyNumber": 2040,
    "requestType": "GetCmdMessageReqBody",
    "responseBodyField": "get_cmd_message_body",
    "responseBodyNumber": 2040,
    "responseType": "GetCmdMessageRespBody"
  },
  {
    "cmd": 2041,
    "symbol": "GET_MESSAGE_INFO_BY_INDEX_V2_RANGE",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_message_info_by_index_v2_range_body",
    "requestBodyNumber": 2041,
    "requestType": "GetMessageInfoByIndexV2RangeRequestBody",
    "responseBodyField": "get_message_info_by_index_v2_range_body",
    "responseBodyNumber": 2041,
    "responseType": "GetMessageInfoByIndexV2RangeResponseBody"
  },
  {
    "cmd": 2042,
    "symbol": "BATCH_GET_CONVERSATION_AUDIT_UNREAD",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "batch_get_conversation_audit_unread",
    "requestBodyNumber": 2042,
    "requestType": "BatchGetConversationAuditUnreadRequestBody",
    "responseBodyField": "batch_get_conversation_audit_unread_body",
    "responseBodyNumber": 2042,
    "responseType": "BatchGetConversationAuditUnreadResponseBody"
  },
  {
    "cmd": 2043,
    "symbol": "GET_MESSAGE_BY_INIT",
    "route": "v1/message/get_message_by_init",
    "classification": "http",
    "requestBodyField": "message_by_init",
    "requestBodyNumber": 2043,
    "requestType": "MessageByInitRequestBody",
    "responseBodyField": "message_by_init",
    "responseBodyNumber": 2043,
    "responseType": "MessageByInitResponseBody"
  },
  {
    "cmd": 2044,
    "symbol": "PREVIEWER_GET_MESSAGES_BY_CONVERSATION",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "previewer_messages_in_conversation_body",
    "requestBodyNumber": 2044,
    "requestType": "PreviewerMessagesInConversationRequestBody",
    "responseBodyField": "previewer_messages_in_conversation_body",
    "responseBodyNumber": 2044,
    "responseType": "PreviewerMessagesInConversationResponseBody"
  },
  {
    "cmd": 2045,
    "symbol": "PREVIEWER_GET_CONVERSATION_INFO_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "previewer_get_conversation_info_list_body",
    "requestBodyNumber": 2045,
    "requestType": "PreviewerGetConversationInfoListRequestBody",
    "responseBodyField": "previewer_get_conversation_info_list_body",
    "responseBodyNumber": 2045,
    "responseType": "PreviewerGetConversationInfoListResponseBody"
  },
  {
    "cmd": 2046,
    "symbol": "SEND_FRIEND_APPLY",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "send_friend_apply_body",
    "requestBodyNumber": 2046,
    "requestType": "SendFriendApplyRequestBody",
    "responseBodyField": "send_friend_apply_body",
    "responseBodyNumber": 2046,
    "responseType": "SendFriendApplyResponseBody"
  },
  {
    "cmd": 2047,
    "symbol": "GET_FRIEND_APPLY_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_friend_apply_list_body",
    "requestBodyNumber": 2047,
    "requestType": "GetFriendApplyListRequestBody",
    "responseBodyField": "get_friend_apply_list_body",
    "responseBodyNumber": 2047,
    "responseType": "GetFriendApplyListResponseBody"
  },
  {
    "cmd": 2048,
    "symbol": "GET_FRIEND_RECEIVE_APPLY_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_friend_receive_apply_list_body",
    "requestBodyNumber": 2048,
    "requestType": "GetFriendReceiveApplyListRequestBody",
    "responseBodyField": "get_friend_receive_apply_list_body",
    "responseBodyNumber": 2048,
    "responseType": "GetFriendReceiveApplyListResponseBody"
  },
  {
    "cmd": 2049,
    "symbol": "REPLY_FRIEND_APPLY",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "reply_friend_apply_body",
    "requestBodyNumber": 2049,
    "requestType": "ReplyFriendApplyRequestBody",
    "responseBodyField": "reply_friend_apply_body",
    "responseBodyNumber": 2049,
    "responseType": "ReplyFriendApplyResponseBody"
  },
  {
    "cmd": 2050,
    "symbol": "GET_FRIEND_LIST",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "get_friend_list_body",
    "requestBodyNumber": 2050,
    "requestType": "GetFriendListRequestBody",
    "responseBodyField": "get_friend_list_body",
    "responseBodyNumber": 2050,
    "responseType": "GetFriendListResponseBody"
  },
  {
    "cmd": 2051,
    "symbol": "DELETE_FRIEND",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "delete_friend_body",
    "requestBodyNumber": 2051,
    "requestType": "DeleteFriendRequestBody",
    "responseBodyField": "delete_friend_body",
    "responseBodyNumber": 2051,
    "responseType": "DeleteFriendResponseBody"
  },
  {
    "cmd": 2052,
    "symbol": "PROFILE_BATCH_GET_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "profile_batch_get_info_body",
    "requestBodyNumber": 2052,
    "requestType": "ProfileBatchGetInfoRequestBody",
    "responseBodyField": "profile_batch_get_info_body",
    "responseBodyNumber": 2052,
    "responseType": "ProfileBatchGetInfoResponseBody"
  },
  {
    "cmd": 2053,
    "symbol": "PROFILE_SEARCH_INFO",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "profile_search_info_body",
    "requestBodyNumber": 2053,
    "requestType": "ProfileSearchInfoRequestBody",
    "responseBodyField": "profile_search_info_body",
    "responseBodyNumber": 2053,
    "responseType": "ProfileSearchInfoResponseBody"
  },
  {
    "cmd": 2054,
    "symbol": "MARK_MSG_UNREAD_COUNT_REPORT",
    "route": "v1/message/report_mark_count",
    "classification": "http",
    "requestBodyField": "mark_msg_unread_count_report",
    "requestBodyNumber": 2054,
    "requestType": "MarkMsgUnreadCountReportRequestBody",
    "responseBodyField": "mark_msg_unread_count_report",
    "responseBodyNumber": 2054,
    "responseType": "MarkMsgUnreadCountReportResponseBody"
  },
  {
    "cmd": 2055,
    "symbol": "MARK_MSG_GET_UNREAD_COUNT",
    "route": "v1/message/get_mark_count",
    "classification": "http",
    "requestBodyField": "mark_msg_get_unread_count",
    "requestBodyNumber": 2055,
    "requestType": "MarkMsgGetUnreadCountRequestBody",
    "responseBodyField": "mark_msg_get_unread_count",
    "responseBodyNumber": 2055,
    "responseType": "MarkMsgGetUnreadCountResponseBody"
  },
  {
    "cmd": 2056,
    "symbol": "BATCH_UNMARK_MESSAGE",
    "route": "v1/message/batch_unmark",
    "classification": "http",
    "requestBodyField": "batch_unmark_message",
    "requestBodyNumber": 2056,
    "requestType": "BatchUnmarkMessageRequestBody",
    "responseBodyField": "batch_unmark_message",
    "responseBodyNumber": 2056,
    "responseType": "BatchUnmarkMessageResponseBody"
  },
  {
    "cmd": 2057,
    "symbol": "CLIENT_BATCH_ACK",
    "route": "v1/client/batch_ack",
    "classification": "http",
    "requestBodyField": "client_batch_ack_body",
    "requestBodyNumber": 2057,
    "requestType": "ClientBatchACKRequestBody",
    "responseBodyField": "client_batch_ack_body",
    "responseBodyNumber": 2057,
    "responseType": "ClientBatchACKResponseBody"
  },
  {
    "cmd": 2058,
    "symbol": "JOIN_VOIP",
    "route": null,
    "classification": "enum-only",
    "requestBodyField": null,
    "requestBodyNumber": null,
    "requestType": null,
    "responseBodyField": null,
    "responseBodyNumber": null,
    "responseType": null
  },
  {
    "cmd": 2059,
    "symbol": "GET_MEDIA_UPLOAD_CONFIG",
    "route": "v1/media/upload_config",
    "classification": "http",
    "requestBodyField": "media_upload_config_request_body",
    "requestBodyNumber": 2059,
    "requestType": "GetMediaUploadConfigRequestBody",
    "responseBodyField": "media_upload_config_response_body",
    "responseBodyNumber": 2059,
    "responseType": "GetMediaUploadConfigResponseBody"
  },
  {
    "cmd": 2060,
    "symbol": "GET_MEDIA_STATUS",
    "route": "v1/media/get_status",
    "classification": "http",
    "requestBodyField": "media_status_request_body",
    "requestBodyNumber": 2060,
    "requestType": "GetMediaStatusRequestBody",
    "responseBodyField": "media_status_response_body",
    "responseBodyNumber": 2060,
    "responseType": "GetMediaStatusResponseBody"
  },
  {
    "cmd": 2100,
    "symbol": "GLOBAL_MESSAGE_SEARCH",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "global_message_search_body",
    "requestBodyNumber": 2100,
    "requestType": "GlobalMessageSearchRequestBody",
    "responseBodyField": "global_message_search_body",
    "responseBodyNumber": 2100,
    "responseType": "GlobalMessageSearchResponseBody"
  },
  {
    "cmd": 2101,
    "symbol": "GLOBAL_GROUP_SEARCH",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "conversation_core_search_body",
    "requestBodyNumber": 2101,
    "requestType": "ConversationCoreSearchRequestBody",
    "responseBodyField": "conversation_core_search_body",
    "responseBodyNumber": 2101,
    "responseType": "ConversationCoreSearchResponseBody"
  },
  {
    "cmd": 2102,
    "symbol": "CONVERSATION_MESSAGE_SEARCH",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "conversation_message_search_body",
    "requestBodyNumber": 2102,
    "requestType": "ConversationMessageSearchRequestBody",
    "responseBodyField": "conversation_message_search_body",
    "responseBodyNumber": 2102,
    "responseType": "ConversationMessageSearchResponseBody"
  },
  {
    "cmd": 2103,
    "symbol": "CONVERSATION_MESSAGE_PRE_VIEW",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "conversation_message_pre_view_body",
    "requestBodyNumber": 2103,
    "requestType": "ConversationMessagePreViewRequestBody",
    "responseBodyField": "conversation_message_pre_view_body",
    "responseBodyNumber": 2103,
    "responseType": "ConversationMessagePreViewResponseBody"
  },
  {
    "cmd": 2200,
    "symbol": "GET_MESSAGES",
    "route": "v1/message/get",
    "classification": "http",
    "requestBodyField": "get_messages_body",
    "requestBodyNumber": 2200,
    "requestType": "GetMessagesRequestBody",
    "responseBodyField": "get_messages_body",
    "responseBodyNumber": 2200,
    "responseType": "GetMessagesResponseBody"
  },
  {
    "cmd": 9999,
    "symbol": "VCD_CLEAN",
    "route": null,
    "classification": "proto-no-route",
    "requestBodyField": "vcd_clean_body",
    "requestBodyNumber": 9999,
    "requestType": "VcdCleanRequestBody",
    "responseBodyField": "vcd_clean_body",
    "responseBodyNumber": 9999,
    "responseType": "VcdCleanResponseBody"
  }
] as const satisfies readonly TikTokApiEntry[];

export type TikTokApiRegistryEntry = (typeof TIKTOK_IM_API)[number];

export const TIKTOK_IM_API_BY_CMD =
  new Map<number, TikTokApiRegistryEntry>(
    TIKTOK_IM_API.map((entry) => [entry.cmd, entry])
  );

export const TIKTOK_IM_API_BY_SYMBOL =
  new Map<string, TikTokApiRegistryEntry>(
    TIKTOK_IM_API.map((entry) => [entry.symbol, entry])
  );

export function getApiByCmd(cmd: number): TikTokApiRegistryEntry | undefined {
  return TIKTOK_IM_API_BY_CMD.get(cmd);
}

export function getApiBySymbol(symbol: string): TikTokApiRegistryEntry | undefined {
  return TIKTOK_IM_API_BY_SYMBOL.get(symbol);
}
